### ISSUE TITLE
Syntax error in README.md

### ISSUE THREAD

**Issue by yobabyface** [Un-index/WhatsappFastSpam#2]
I found a syntax error literally on the preface such sloppy work try harder buddy

**Comment by deontic** [comment]
If you’re creating an issue it might be worth pointing out what you’re talking about.

**Comment by deontic** [comment]
I’m sure you’re running that in your terminal and not as JavaScript ? There’s no code in the README file that can be run directly as JavaScript. 

I’ve tested everything myself so this issue can’t be valid.
